more prints

diff --git a/.github/workflows/generate-test-ray.yaml b/.github/workflows/generate-test-ray.yaml
--- a/.github/workflows/generate-test-ray.yaml
+++ b/.github/workflows/generate-test-ray.yaml
@@ -5,6 +5,16 @@ on:
 jobs:
   detect-changes:
     runs-on: ubuntu-latest
+    outputs:
+      src: ${{ steps.filter.outputs.src }}
+      test: ${{ steps.filter.outputs.test }}
+      feature_specs: ${{ steps.filter.outputs.feature_specs }}
+      hello: ${{ steps.filter.outputs.changes }} 
+      
+      src_files: ${{ steps.filter.outputs.src_files }}
+      test_files: ${{ steps.filter.outputs.test_files }}
+      feature_specs_files: ${{ steps.filter.outputs.feature_specs_files }}
+      hello_files: ${{ steps.filter.outputs.changes_files }} 
     steps:
       - uses: actions/checkout@v3
 
@@ -45,56 +55,56 @@ jobs:
           echo '${{ needs.detect-changes.outputs.feature_specs }}'
           echo '${{ needs.detect-changes.outputs.src }}'
           echo '${{ needs.detect-changes.outputs.test }}'
-          echo '${{ needs.detect-changes.outputs.changes }}'
+          echo '${{ needs.detect-changes.outputs.hello }}'
 
+          echo '${{ needs.detect-changes.outputs.feature_specs_files }}'
           echo '${{ needs.detect-changes.outputs.src_files }}'
           echo '${{ needs.detect-changes.outputs.test_files }}'
-
-          echo '${{ needs.detect-changes.outputs.changes_files }}'
-
+          echo '${{ needs.detect-changes.outputs.hello_files }}'
 
 
-      # - name: Shell Linter
-      #   uses: azohra/shell-linter@v0.6.0
-      #   with:
-      #     path: "src/**/*.sh"
-      #     severity: "error" # [style, info, warning, error]
-      #   env:
-      #     SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison
 
-      # - name: "Install latest devcontainer CLI"
-      #   run: npm install -g @devcontainers/cli
+      - name: Shell Linter
+        uses: azohra/shell-linter@v0.6.0
+        with:
+          path: "src/**/*.sh"
+          severity: "error" # [style, info, warning, error]
+        env:
+          SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison
 
-      # - name: "Install test requirements"
-      #   run: |
-      #     python3 -m pip install -r requirements-tests.txt
+      - name: "Install latest devcontainer CLI"
+        run: npm install -g @devcontainers/cli
 
-      # - name: "install generator"
-      #   run: |
-      #     pipx install cookiecutter
-      #     pipx install shfmt-py
+      - name: "Install test requirements"
+        run: |
+          python3 -m pip install -r requirements-tests.txt
 
-      # - name: Generate
-      #   id: generate
-      #   run: |
-      #     set -e
-      #     cd ..
-      #     jq -c '.[]' <<< '${{ needs.find-feature.outputs.generated_features }}' | while read i; do
-      #         cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/$(echo $i | tr -d '"').yaml 
-      #     done
-      #     cd features
+      - name: "install generator"
+        run: |
+          pipx install cookiecutter
+          pipx install shfmt-py
+
+      - name: Generate
+        id: generate
+        run: |
+          set -e
+          cd ..
+          jq -c '.[]' <<< '${{ needs.find-feature.outputs.generated_features }}' | while read i; do
+              cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/$(echo $i | tr -d '"').yaml 
+          done
+          cd features
         
-      # - name: "Running tests"
-      #   run: |
-      #     docker pull mcr.microsoft.com/devcontainers/base:debian
-      #     cd tests
-      #     export RAY_ROTATION_MAX_BYTES=1024000
-      #     export RAY_ROTATION_BACKUP_COUNT=1
+      - name: "Running tests"
+        run: |
+          docker pull mcr.microsoft.com/devcontainers/base:debian
+          cd tests
+          export RAY_ROTATION_MAX_BYTES=1024000
+          export RAY_ROTATION_BACKUP_COUNT=1
 
-      #     ray start --head --port=6379
+          ray start --head --port=6379
    
-      #     python3 -u -m pytest test_all_features.py -s --base_dir $GITHUB_WORKSPACE --image "mcr.microsoft.com/devcontainers/base:debian" --feature_ids '${{ needs.find-feature.outputs.all_features }}'
-      #     cd ..
+          python3 -u -m pytest test_all_features.py -s --base_dir $GITHUB_WORKSPACE --image "mcr.microsoft.com/devcontainers/base:debian" --feature_ids '${{ needs.find-feature.outputs.all_features }}'
+          cd ..
 
   test-global:
     runs-on: ubuntu-latest
