test prints

diff --git a/.github/workflows/generate-test-ray.yaml b/.github/workflows/generate-test-ray.yaml
--- a/.github/workflows/generate-test-ray.yaml
+++ b/.github/workflows/generate-test-ray.yaml
@@ -3,6 +3,18 @@ on:
   workflow_dispatch:
   push:
 jobs:
+  detect-changes:
+    runs-on: ubuntu-latest
+    outputs:
+      changes: ${{ steps.filter.outputs.changes }}
+    steps:
+      - uses: dorny/paths-filter@v2
+        id: filter
+        with:
+          filters: |
+            src: ./src/**/**
+            test: ./test/**/**
+            feature_specs: ./feature_specs/**
 
   find-feature:
     if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
@@ -19,50 +31,54 @@ jobs:
           path: .
 
   test:
-    needs: [find-feature]
+    needs: [find-feature, detect-changes]
 
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
       - uses: actions/checkout@v3
-      
-      - name: Shell Linter
-        uses: azohra/shell-linter@v0.6.0
-        with:
-          path: "src/**/*.sh"
-          severity: "error" # [style, info, warning, error]
-        env:
-          SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison
 
-      - name: "Install latest devcontainer CLI"
-        run: npm install -g @devcontainers/cli
-
-      - name: "Install test requirements"
+      - name: "test changes"
         run: |
-          python3 -m pip install -r requirements-tests.txt
+          echo '${{ needs.detect-changes.outputs.changes }}'
 
-      - name: "install generator"
-        run: |
-          pipx install cookiecutter
-          pipx install shfmt-py
+      # - name: Shell Linter
+      #   uses: azohra/shell-linter@v0.6.0
+      #   with:
+      #     path: "src/**/*.sh"
+      #     severity: "error" # [style, info, warning, error]
+      #   env:
+      #     SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison
 
-      - name: Generate
-        id: generate
-        run: |
-          set -e
-          cd ..
-          jq -c '.[]' <<< '${{ needs.find-feature.outputs.generated_features }}' | while read i; do
-              cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/$(echo $i | tr -d '"').yaml 
-          done
-          cd features
+      # - name: "Install latest devcontainer CLI"
+      #   run: npm install -g @devcontainers/cli
+
+      # - name: "Install test requirements"
+      #   run: |
+      #     python3 -m pip install -r requirements-tests.txt
+
+      # - name: "install generator"
+      #   run: |
+      #     pipx install cookiecutter
+      #     pipx install shfmt-py
+
+      # - name: Generate
+      #   id: generate
+      #   run: |
+      #     set -e
+      #     cd ..
+      #     jq -c '.[]' <<< '${{ needs.find-feature.outputs.generated_features }}' | while read i; do
+      #         cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/$(echo $i | tr -d '"').yaml 
+      #     done
+      #     cd features
         
-      - name: "Running tests"
-        run: |
-          docker pull mcr.microsoft.com/devcontainers/base:debian
-          cd tests
-          ray start --head --port=6379
-          python3 -m pytest test_all_features.py -s --base_dir $GITHUB_WORKSPACE --image "mcr.microsoft.com/devcontainers/base:debian" --feature_ids '${{ needs.find-feature.outputs.all_features }}'
-          cd ..
+      # - name: "Running tests"
+      #   run: |
+      #     docker pull mcr.microsoft.com/devcontainers/base:debian
+      #     cd tests
+      #     ray start --head --port=6379
+      #     python3 -m pytest test_all_features.py -s --base_dir $GITHUB_WORKSPACE --image "mcr.microsoft.com/devcontainers/base:debian" --feature_ids '${{ needs.find-feature.outputs.all_features }}'
+      #     cd ..
 
   test-global:
     runs-on: ubuntu-latest
